# 基础镜像
FROM nginx
# author
MAINTAINER jiron

# 挂载目录
VOLUME /home/jiron/projects/jiron-ui
# 创建目录
RUN mkdir -p /home/jiron/projects/jiron-ui
# 指定路径
WORKDIR /home/jiron/projects/jiron-ui
# 复制conf文件到路径
COPY ./conf/nginx.conf /etc/nginx/nginx.conf
# 复制html文件到路径
COPY ./html/dist /home/jiron/projects/jiron-ui
